# **Installations**

In [ ]:
!pip install faker
!pip install openpyxl

Collecting faker
  Downloading Faker-23.3.0-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 9.4 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->faker) (1.16.0)
Installing collected packages: faker
Successfully installed faker-23.3.0
Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.1.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (1.1.0)

# **Importations**

In [ ]:
# Imprting libraries

import pandas as pd
import numpy as np
from faker import Faker
import random
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# **Instances**

In [ ]:
fake = Faker('es_ES')

# **Helping functions**

In [ ]:
# Helping functions to create DataFrames for each entity

# Helping functions for Restaurants



def generate_restaurant_name():
  preffixes = ['Café', 'Bar', 'Restaurante', 'Bistro', 'Tasca']
  names = ['Rincón de', 'Casa de', 'Jardín de', 'Terraza de', 'Parrilla', 'Marisquería', 'Cantina', 'Taberna', 'Bar Restaurante', 'Hospederia']
  subjects = ['Rosa', 'Carlos', 'Mar', 'Sol', 'Luna', 'Tierra', 'Luces', 'Sabor', 'Aroma']
  sufixess = ['', ' Gourmet', ' del Puerto', ' de la Playa', ' del Río', ' de la Montaña', ' Urbano', ' del Bosque', 'de Barcelona', 'Madrid', 'de Málaga', 'exclusivo', 'cuchara brava', 'guay', 'brasa criolla', 'sanguchería', '4 estaciones']
  preffix = random.choice(preffixes)
  name = random.choice(names)
  subject = random.choice(subjects)
  suffix = random.choice(sufixess)

  full_restaurant_name = f"{preffix} {name} {subject} {suffix}"
  return full_restaurant_name

def generate_cuisine_type():
  cuisines = ['Italian', 'Mexican', 'Chinese', 'Japanise', 'American', 'Indian', 'French', 'Thai']
  return random.choice(cuisines)

def generate_restaurant_size():
    sizes = ['Small', 'Medium', 'Large']
    return random.choice(sizes)

def generate_price_range():
    price_ranges = ['$', '$$', '$$$', '$$$$']
    return random.choice(price_ranges)

# Helping functions for Products

def generate_product_category():
    categories = ['Dairy', 'Meat', 'Bakery', 'Beverages', 'Seafood', 'Vegetables', 'Fruits', 'Dry Goods']
    return random.choice(categories)

def generate_product_price(category):
    if category in ['Meat', 'Seafood']:
        return round(random.uniform(5, 25), 2)
    else:
        return round(random.uniform(1, 10), 2)

def generate_product_name(category):
  return fake.word().capitalize()

# Helping functions for Suppliers



def generate_supplier_name():
  preffixes = ['Tiendas', 'Red de', 'Almacenes', 'Importadora', 'Comercializadora', 'Exportador', 'Proveedor', 'Distribuciones', 'Productor', 'Supermercados']
  names = ['Sabores de', 'Delicias de', 'Especialiades', 'Productos de', 'Gastronomía', 'Alimentos', 'Ibéricos', 'Mediterraneos', 'Gourmet']
  subjects = ['Andalucía', 'Galicia', 'Valencia', 'Cataluña', 'La Rioja', 'Asturias', 'Canarias', 'Euskadi', 'Castilla']
  suffixes = ['', ' y compañia', ' hermanos', ' e hijos', ' selectos', ' premium', ' tradicionales', ' artesanales', 'internacionales', 'del mar']
  preffix = random.choice(preffixes)
  name = random.choice(names)
  subject = random.choice(subjects)
  suffix = random.choice(suffixes)

  full_supplier_name = f"{preffix} {name} {subject} {suffix}"
  return full_supplier_name

def generate_supplier_specialty():
    specialties = ['General', 'Dairy', 'Meat', 'Bakery', 'Beverages', 'Seafood', 'Produce']  # Produce incluye Vegetales y Frutas
    return random.choice(specialties)

# Helping functions for Orders

def generate_order_date():
    start_date = pd.to_datetime("2023-01-01")
    end_date = pd.to_datetime("2023-12-31")

    time_between_dates = end_date - start_date
    days_between_dates = time_between_dates.days
    random_number_of_days = random.randrange(days_between_dates)
    random_date = start_date + pd.Timedelta(days=random_number_of_days)

    return random_date

def generate_order_quantity():
    return random.randint(1, 100)
# Generar Precio Total del Pedido - Podrías calcular el precio total del pedido en función de los productos seleccionados y sus cantidades, en lugar de generarlo aleatoriamente. Esto aseguraría que el precio total refleje el costo real de los productos en el pedido.

# **Individual entity dataframes**

In [ ]:
# Data simulation for each entity

#--------------------------Restaurants-----------------------------------------------------#

num_restaurants = 100

restaurant_data = {
    'Restaurant ID': range(1, num_restaurants + 1),
    'Name': [generate_restaurant_name() for _ in range(num_restaurants)],
    'Location': [fake.address() for _ in range(num_restaurants)],
    'Cuisine Type': [generate_cuisine_type() for _ in range(num_restaurants)],
    'Size': [random.choice(['Small', 'Medium', 'Large']) for _ in range(num_restaurants)],
    'Price Range': [random.choice(['$', '$$', '$$$', '$$$$']) for _ in range(num_restaurants)]
}

restaurants_df = pd.DataFrame(restaurant_data)

#--------------------------Products-----------------------------------------------------#

num_products = 500

product_categories = [generate_product_category() for _ in range(num_products)]

product_data = {
    'Product ID': range(1, num_products +1 ),
    'Name': [generate_product_name(category) for category in product_categories],
    'Category': product_categories,
    'Product price': [generate_product_price(category) for category in product_categories],
    'Supplier ID': [random.randint(1, 50) for _ in range(num_products)],
}

products_df = pd.DataFrame(product_data)


#--------------------------Suppliers-----------------------------------------------------#

num_suppliers = 500

suppliers_data = {
    'Supplier ID': range(1, num_suppliers + 1),
    'Name': [generate_supplier_name() for _ in range(num_suppliers)],
    'Location': [fake.address() for _ in range(num_suppliers)],
    'Speciality': [generate_supplier_specialty() for _ in range(num_suppliers)]

}

suppliers_df = pd.DataFrame(suppliers_data)



#--------------------------Orders-----------------------------------------------------#

num_orders = 1000

restaurants_df.reset_index(drop=True, inplace=True)
products_df.reset_index(drop=True, inplace=True)

order_data = {
    'Order ID': range(1, num_orders + 1),
    'Restaurant ID': restaurants_df['Restaurant ID'].sample(n=num_orders, replace=True).values,
    'Product ID': products_df['Product ID'].sample(n=num_orders, replace=True).values,
    'Order date': [generate_order_date() for _ in range(num_orders)],
    'Quantity': [generate_order_quantity() for _ in range(num_orders)],
}

orders_df = pd.DataFrame(order_data)

#Calculating total order price - Multiplying Product ID in product_data * quantity in order_data

# 1- creating a mapping of Product ID to price

price_map = products_df.set_index('Product ID')['Product price'].to_dict()

# 2- Assign prices to orders and calculate total price

orders_df['Price'] = orders_df['Product ID'].map(price_map)

orders_df['Total Price'] = (orders_df['Price'] * orders_df['Quantity']).round(2)


#restaurants_df # activate to see the data frame
#products_df # activate to see the data frame
#suppliers_df # activate to see the data frame
#orders_df # activate to see the data frame

# **Data relationships verification**

In [ ]:
#-----------------------------Orders-Restaurants Relationships-------------------------#
#Every Restaurant ID in orders_df should exist in restaurant_df

orders_restaurants_check = orders_df['Restaurant ID'].isin(restaurants_df['Restaurant ID']).all()
if orders_restaurants_check:
  print ('All restaurant IDs in orders are valid')
else:
  print('There are orders with non-valid Restaurant ID')

#-----------------------------Orders-Products Relationships-------------------------#
#Every Product ID in orders_df should exist in products_df

orders_products_check = orders_df['Product ID'].isin(products_df['Product ID']).all()
if orders_restaurants_check:
  print('All Product IDs in orders are valid')
else:
  print('There are orders with non-valid Product ID')

#-----------------------------Products-Suppliers Relationships-------------------------#
#Every Supplier ID in products_df should exist in suppliers_df

products_suppliers_check = products_df['Supplier ID'].isin(suppliers_df['Supplier ID']).all()
if products_suppliers_check:
  print('All Suppliers IDs in products are valid')
else:
  print('There are products with non-valid Supplier ID')

All restaurant IDs in orders are valid
All Product IDs in orders are valid
All Suppliers IDs in products are valid

# **Data visualization**

In [ ]:
'''
display(restaurants_df)
display(products_df)
display(suppliers_df)
display(orders_df)
'''
display(orders_df)

,Order ID,Restaurant ID,Product ID,Order date,Quantity,Price,Total Price
0,1,1,299,2023-12-17,45,5.29,238.05
1,2,64,227,2023-02-11,63,3.33,209.79
2,3,10,378,2023-04-17,50,9.06,453.00
3,4,62,410,2023-07-13,85,9.84,836.40
4,5,44,31,2023-05-24,35,11.19,391.65
...,...,...,...,...,...,...,...
995,996,68,291,2023-06-29,72,2.30,165.60
996,997,83,255,2023-12-26,23,5.31,122.13
997,998,11,157,2023-08-29,65,7.48,486.20
998,999,9,379,2023-12-17,94,5.31,499.14
999,1000,86,334,2023-01-29,78,2.68,209.04

# **Export**

In [ ]:
path = '/content/drive/My Drive/Data Science/Recommendation system Raiil/data/simulated/'
restaurants_df.to_excel(f'{path}restaurants.xlsx', index=False, engine='openpyxl')
products_df.to_excel(f'{path}products.xlsx', index=False, engine='openpyxl')
suppliers_df.to_excel(f'{path}suppliers.xlsx', index=False, engine='openpyxl')
orders_df.to_excel(f'{path}orders.xlsx', index=False, engine='openpyxl')